// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFAn080v6KQEQegtxDeH2aH_4y88ZvO5c',
    appId: '1:995647264045:web:bd13ebe777e01d0b906fa4',
    messagingSenderId: '995647264045',
    projectId: 'health-connect-13354',
    authDomain: 'health-connect-13354.firebaseapp.com',
    storageBucket: 'health-connect-13354.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBW2ss-JsHOAZxo--RinSwnOq6BnVxbLEI',
    appId: '1:995647264045:android:14013d69a18fa984906fa4',
    messagingSenderId: '995647264045',
    projectId: 'health-connect-13354',
    storageBucket: 'health-connect-13354.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAEXWUU49RvdzXdJC20bxKvxbHYdZ5mHI',
    appId: '1:995647264045:ios:4782147fb9140483906fa4',
    messagingSenderId: '995647264045',
    projectId: 'health-connect-13354',
    storageBucket: 'health-connect-13354.firebasestorage.app',
    iosBundleId: 'com.example.healthConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAEXWUU49RvdzXdJC20bxKvxbHYdZ5mHI',
    appId: '1:995647264045:ios:4782147fb9140483906fa4',
    messagingSenderId: '995647264045',
    projectId: 'health-connect-13354',
    storageBucket: 'health-connect-13354.firebasestorage.app',
    iosBundleId: 'com.example.healthConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFAn080v6KQEQegtxDeH2aH_4y88ZvO5c',
    appId: '1:995647264045:web:90ee412d57ec3b41906fa4',
    messagingSenderId: '995647264045',
    projectId: 'health-connect-13354',
    authDomain: 'health-connect-13354.firebaseapp.com',
    storageBucket: 'health-connect-13354.firebasestorage.app',
  );
}
