import 'package:flutter/material.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:fl_chart/fl_chart.dart';

class HospitalDeepAnalyticsPage extends StatefulWidget {
  final String hospitalId;
  final String hospitalName;

  const HospitalDeepAnalyticsPage({
    super.key,
    required this.hospitalId,
    required this.hospitalName,
  });

  @override
  State<HospitalDeepAnalyticsPage> createState() => _HospitalDeepAnalyticsPageState();
}

class _HospitalDeepAnalyticsPageState extends State<HospitalDeepAnalyticsPage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: const Color(0xFFF1F5F9),
      appBar: AppBar(
        title: Text(widget.hospitalName, style: const TextStyle(fontWeight: FontWeight.bold, color: Color(0xFF0F172A))),
        backgroundColor: Colors.white,
        foregroundColor: Colors.black,
        elevation: 0,
      ),
      body: FutureBuilder<Map<String, dynamic>>(
        future: _fetchAllHospitalData(),
        builder: (context, snapshot) {
          if (!snapshot.hasData) return const Center(child: CircularProgressIndicator());
          
          final data = snapshot.data!;
          final docRevenue = data['docRevenue'] as Map<String, double>;
          final patientRevenue = data['patientRevenue'] as Map<String, double>;
          final serviceMix = data['serviceMix'] as Map<String, int>;
          final totalRevenue = data['totalRevenue'] as double;

          return SingleChildScrollView(
            padding: const EdgeInsets.all(20),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                _buildPremiumHero(totalRevenue, data['totalRecords'] as int, data['uniquePatients'] as int),
                const SizedBox(height: 28),
                
                _buildSectionHeader("PERFORMANCE RANKINGS", "Monthly revenue generated by top-performing doctors in this hospital."),
                const SizedBox(height: 16),
                _PremiumDoctorBarChart(docRevenue: docRevenue),
                
                const SizedBox(height: 28),
                
                Row(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Expanded(
                      child: _GlassCard(
                        title: "SERVICE DISTRIBUTION",
                        subtitle: "Breakdown of consultation types.",
                        child: _ModernDonutChart(serviceMix: serviceMix),
                      ),
                    ),
                    const SizedBox(width: 16),
                    Expanded(
                      child: _GlassCard(
                        title: "TOP REVENUE SOURCES",
                        subtitle: "Highest paying patient accounts.",
                        child: _PatientImpactList(patientRevenue: patientRevenue),
                      ),
                    ),
                  ],
                ),
                
                const SizedBox(height: 28),
                _buildSectionHeader("FINANCIAL DENSITY TREND", "Historical visualization of total revenue flow from all clinical activities per transaction."),
                const SizedBox(height: 16),
                _PremiumRevenueAreaChart(allRecords: data['allRecords'] as List<Map<String, dynamic>>),
                const SizedBox(height: 40),
              ],
            ),
          );
        },
      ),
    );
  }

  Widget _buildSectionHeader(String title, String subtitle) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          title,
          style: const TextStyle(fontSize: 12, letterSpacing: 1.2, fontWeight: FontWeight.w800, color: Color(0xFF64748B)),
        ),
        const SizedBox(height: 4),
        Text(
          subtitle,
          style: const TextStyle(fontSize: 11, color: Color(0xFF94A3B8), fontWeight: FontWeight.w500),
        ),
      ],
    );
  }

  Widget _buildPremiumHero(double revenue, int records, int patients) {
    return Container(
      width: double.infinity,
      padding: const EdgeInsets.all(28),
      decoration: BoxDecoration(
        gradient: const LinearGradient(
          colors: [Color(0xFF0F172A), Color(0xFF1E293B)],
          begin: Alignment.topLeft,
          end: Alignment.bottomRight,
        ),
        borderRadius: BorderRadius.circular(24),
        boxShadow: [
          BoxShadow(color: const Color(0xFF0F172A).withOpacity(0.2), blurRadius: 20, offset: const Offset(0, 10))
        ],
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              const Text("Hospital Global Revenue", style: TextStyle(color: Colors.white60, fontSize: 13, fontWeight: FontWeight.w500)),
              Container(
                padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 4),
                decoration: BoxDecoration(color: const Color(0xFF10B981).withOpacity(0.2), borderRadius: BorderRadius.circular(20)),
                child: Row(
                  children: const [
                    Icon(Icons.trending_up, color: Color(0xFF10B981), size: 14),
                    SizedBox(width: 4),
                    Text("+12.5%", style: TextStyle(color: Color(0xFF10B981), fontSize: 11, fontWeight: FontWeight.bold)),
                  ],
                ),
              ),
            ],
          ),
          const SizedBox(height: 12),
          Text(
            "\u20B9${revenue.toStringAsFixed(0)}",
            style: const TextStyle(color: Colors.white, fontSize: 36, fontWeight: FontWeight.w900, letterSpacing: -1),
          ),
          const SizedBox(height: 24),
          Row(
            children: [
              _heroStat(records.toString(), "Records", Icons.description_outlined),
              const SizedBox(width: 32),
              _heroStat(patients.toString(), "Patients", Icons.people_outline),
            ],
          ),
        ],
      ),
    );
  }

  Widget _heroStat(String value, String label, IconData icon) {
    return Row(
      children: [
        Icon(icon, color: Colors.white38, size: 18),
        const SizedBox(width: 8),
        Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(value, style: const TextStyle(color: Colors.white, fontWeight: FontWeight.bold, fontSize: 16)),
            Text(label, style: const TextStyle(color: Colors.white38, fontSize: 10)),
          ],
        ),
      ],
    );
  }

  Future<Map<String, dynamic>> _fetchAllHospitalData() async {
    double totalRevenue = 0;
    Map<String, double> docRevenue = {};
    Map<String, double> patientRevenue = {};
    Map<String, int> serviceMix = {'Scans': 0, 'Treatments': 0};
    List<Map<String, dynamic>> allRecords = [];

    final docSnapshot = await FirebaseFirestore.instance.collection('accounts')
        .where('role', isEqualTo: 'doctor')
        .where('hospitalId', isEqualTo: widget.hospitalId)
        .get();
    Map<String, String> doctorNames = {
      for (var doc in docSnapshot.docs) doc.id: (doc.data()['doctorName'] ?? 'Dr. Unknown')
    };

    final scanSnap = await FirebaseFirestore.instance.collection('scans')
        .where('hospitalId', isEqualTo: widget.hospitalId).get();
    for (var doc in scanSnap.docs) {
      final d = doc.data();
      final cost = (d['cost'] ?? 0.0);
      final timestamp = d['timestamp'] ?? d['createdAt'];
      if (timestamp != null) {
        totalRevenue += cost;
        docRevenue[d['doctorId'] ?? 'unknown'] = (docRevenue[d['doctorId']] ?? 0) + cost;
        patientRevenue[d['patientId'] ?? 'unknown'] = (patientRevenue[d['patientId']] ?? 0) + cost;
        serviceMix['Scans'] = (serviceMix['Scans'] ?? 0) + 1;
        allRecords.add({'timestamp': timestamp, 'cost': cost});
      }
    }

    final treatSnap = await FirebaseFirestore.instance.collection('treatments')
        .where('hospitalId', isEqualTo: widget.hospitalId).get();
    for (var doc in treatSnap.docs) {
      final d = doc.data();
      final cost = (d['cost'] ?? 0.0);
      final timestamp = d['timestamp'] ?? d['createdAt'];
      if (timestamp != null) {
        totalRevenue += cost;
        docRevenue[d['doctorId'] ?? 'unknown'] = (docRevenue[d['doctorId']] ?? 0) + cost;
        patientRevenue[d['patientId'] ?? 'unknown'] = (patientRevenue[d['patientId']] ?? 0) + cost;
        serviceMix['Treatments'] = (serviceMix['Treatments'] ?? 0) + 1;
        allRecords.add({'timestamp': timestamp, 'cost': cost});
      }
    }

    Map<String, double> docRevenueNamed = {};
    docRevenue.forEach((id, rev) {
      docRevenueNamed[doctorNames[id] ?? "Dr. Guest"] = rev;
    });

    return {
      'totalRevenue': totalRevenue,
      'docRevenue': docRevenueNamed,
      'patientRevenue': patientRevenue,
      'serviceMix': serviceMix,
      'totalRecords': scanSnap.docs.length + treatSnap.docs.length,
      'uniquePatients': patientRevenue.length,
      'allRecords': allRecords,
    };
  }
}

class _GlassCard extends StatelessWidget {
  final String title;
  final String subtitle;
  final Widget child;
  const _GlassCard({required this.title, required this.subtitle, required this.child});

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: const EdgeInsets.all(20),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(20),
        border: Border.all(color: Colors.white, width: 2),
        boxShadow: [BoxShadow(color: Colors.black.withOpacity(0.03), blurRadius: 10, offset: const Offset(0, 4))],
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(title, style: const TextStyle(fontSize: 10, fontWeight: FontWeight.w800, color: Color(0xFF94A3B8))),
          const SizedBox(height: 2),
          Text(subtitle, style: const TextStyle(fontSize: 9, color: Color(0xFFCBD5E1), fontWeight: FontWeight.w500)),
          const SizedBox(height: 20),
          child,
        ],
      ),
    );
  }
}

class _PremiumDoctorBarChart extends StatelessWidget {
  final Map<String, double> docRevenue;
  const _PremiumDoctorBarChart({required this.docRevenue});

  @override
  Widget build(BuildContext context) {
    final sorted = docRevenue.entries.toList()..sort((a, b) => b.value.compareTo(a.value));
    final display = sorted.take(5).toList();

    return Container(
      padding: const EdgeInsets.all(24),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(24),
        boxShadow: [BoxShadow(color: Colors.black.withOpacity(0.03), blurRadius: 15, offset: const Offset(0, 8))],
      ),
      child: Column(
        children: [
          SizedBox(
            height: 200,
            child: BarChart(
              BarChartData(
                gridData: FlGridData(show: true, drawVerticalLine: false, getDrawingHorizontalLine: (v) => FlLine(color: Colors.grey.shade100, strokeWidth: 1)),
                titlesData: FlTitlesData(
                  show: true,
                  rightTitles: AxisTitles(sideTitles: SideTitles(showTitles: false)),
                  topTitles: AxisTitles(sideTitles: SideTitles(showTitles: false)),
                  leftTitles: AxisTitles(
                    sideTitles: SideTitles(
                      showTitles: true,
                      reservedSize: 40,
                      getTitlesWidget: (v, m) => Text("\u20B9${(v/1000).toStringAsFixed(0)}k", style: const TextStyle(fontSize: 9, color: Colors.grey)),
                    ),
                  ),
                  bottomTitles: AxisTitles(
                    sideTitles: SideTitles(
                      showTitles: true,
                      getTitlesWidget: (v, m) {
                        if (v.toInt() < display.length) {
                          return Padding(
                            padding: const EdgeInsets.only(top: 8.0),
                            child: Text(display[v.toInt()].key.split(' ').last, style: const TextStyle(fontSize: 10, fontWeight: FontWeight.bold, color: Color(0xFF64748B))),
                          );
                        }
                        return const SizedBox();
                      },
                    ),
                  ),
                ),
                borderData: FlBorderData(show: false),
                barGroups: List.generate(display.length, (i) => BarChartGroupData(
                  x: i,
                  barRods: [
                    BarChartRodData(
                      toY: display[i].value,
                      gradient: const LinearGradient(colors: [Color(0xFF6366F1), Color(0xFFA855F7)], begin: Alignment.bottomCenter, end: Alignment.topCenter),
                      width: 20,
                      borderRadius: const BorderRadius.only(topLeft: Radius.circular(6), topRight: Radius.circular(6)),
                      backDrawRodData: BackgroundBarChartRodData(show: true, toY: (sorted.first.value == 0 ? 1000 : sorted.first.value) * 1.1, color: Colors.grey.shade50),
                    )
                  ],
                )),
              ),
            ),
          ),
          const SizedBox(height: 16),
          _legendItem(const Color(0xFF6366F1), "Doctor Revenue Breakdown (Top 5)"),
        ],
      ),
    );
  }

  Widget _legendItem(Color color, String label) {
    return Row(
      mainAxisAlignment: MainAxisAlignment.center,
      children: [
        Container(width: 8, height: 8, decoration: BoxDecoration(color: color, borderRadius: BorderRadius.circular(2))),
        const SizedBox(width: 8),
        Text(label, style: const TextStyle(fontSize: 10, color: Color(0xFF94A3B8), fontWeight: FontWeight.w600)),
      ],
    );
  }
}

class _ModernDonutChart extends StatelessWidget {
  final Map<String, int> serviceMix;
  const _ModernDonutChart({required this.serviceMix});

  @override
  Widget build(BuildContext context) {
    final total = serviceMix['Scans']! + serviceMix['Treatments']!;
    return Column(
      children: [
        SizedBox(
          height: 120,
          child: Stack(
            alignment: Alignment.center,
            children: [
              PieChart(
                PieChartData(
                  sections: [
                    PieChartSectionData(color: const Color(0xFF3B82F6), value: serviceMix['Scans']!.toDouble(), radius: 18, showTitle: false),
                    PieChartSectionData(color: const Color(0xFFF59E0B), value: serviceMix['Treatments']!.toDouble(), radius: 18, showTitle: false),
                  ],
                  centerSpaceRadius: 35,
                  sectionsSpace: 4,
                ),
              ),
              Column(
                mainAxisSize: MainAxisSize.min,
                children: [
                  Text(total.toString(), style: const TextStyle(fontSize: 18, fontWeight: FontWeight.w900, color: Color(0xFF0F172A))),
                  const Text("TOTAL", style: TextStyle(fontSize: 8, fontWeight: FontWeight.bold, color: Colors.grey)),
                ],
              ),
            ],
          ),
        ),
        const SizedBox(height: 16),
        _miniLegend(const Color(0xFF3B82F6), "Scans"),
        const SizedBox(height: 4),
        _miniLegend(const Color(0xFFF59E0B), "Treatments"),
      ],
    );
  }

  Widget _miniLegend(Color color, String label) {
    return Row(
      children: [
        Container(width: 6, height: 6, decoration: BoxDecoration(color: color, shape: BoxShape.circle)),
        const SizedBox(width: 6),
        Text(label, style: const TextStyle(fontSize: 9, fontWeight: FontWeight.bold, color: Color(0xFF64748B))),
      ],
    );
  }
}

class _PatientImpactList extends StatelessWidget {
  final Map<String, double> patientRevenue;
  const _PatientImpactList({required this.patientRevenue});

  @override
  Widget build(BuildContext context) {
    final sorted = patientRevenue.entries.toList()..sort((a, b) => b.value.compareTo(a.value));
    final display = sorted.take(3);
    
    return Column(
      children: display.map((e) => Container(
        margin: const EdgeInsets.only(bottom: 12),
        padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 8),
        decoration: BoxDecoration(color: const Color(0xFFF8FAFC), borderRadius: BorderRadius.circular(12)),
        child: Row(
          children: [
            const CircleAvatar(radius: 12, backgroundColor: Colors.white, child: Icon(Icons.person, size: 12, color: Color(0xFF64748B))),
            const SizedBox(width: 8),
            Expanded(child: Text(e.key.length > 8 ? e.key.substring(0, 8) : e.key, style: const TextStyle(fontSize: 10, fontWeight: FontWeight.w600, color: Color(0xFF1E293B)))),
            Text("\u20B9${e.value.toStringAsFixed(0)}", style: const TextStyle(fontSize: 10, fontWeight: FontWeight.w800, color: Color(0xFF0F172A))),
          ],
        ),
      )).toList(),
    );
  }
}

class _PremiumRevenueAreaChart extends StatelessWidget {
  final List<Map<String, dynamic>> allRecords;
  const _PremiumRevenueAreaChart({required this.allRecords});

  @override
  Widget build(BuildContext context) {
    final sorted = allRecords..sort((a, b) => (a['timestamp'] as Timestamp).compareTo(b['timestamp']));
    final lastN = sorted.length > 12 ? sorted.sublist(sorted.length - 12) : sorted;

    return Container(
      padding: const EdgeInsets.all(24),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(24),
        boxShadow: [BoxShadow(color: Colors.black.withOpacity(0.03), blurRadius: 15, offset: const Offset(0, 8))],
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          SizedBox(
            height: 200,
            child: LineChart(
              LineChartData(
                gridData: FlGridData(show: true, drawVerticalLine: false, getDrawingHorizontalLine: (v) => FlLine(color: Colors.grey.shade50, strokeWidth: 1)),
                titlesData: FlTitlesData(
                  show: true,
                  topTitles: AxisTitles(sideTitles: SideTitles(showTitles: false)),
                  rightTitles: AxisTitles(sideTitles: SideTitles(showTitles: false)),
                  leftTitles: AxisTitles(
                    sideTitles: SideTitles(
                      showTitles: true,
                      reservedSize: 40,
                      getTitlesWidget: (v, m) => Text("\u20B9${(v/1000).toStringAsFixed(0)}k", style: const TextStyle(fontSize: 9, color: Colors.grey)),
                    ),
                  ),
                  bottomTitles: AxisTitles(sideTitles: SideTitles(showTitles: false)),
                ),
                borderData: FlBorderData(show: false),
                lineBarsData: [
                  LineChartBarData(
                    spots: List.generate(lastN.length, (i) => FlSpot(i.toDouble(), (lastN[i]['cost'] as double))),
                    isCurved: true,
                    gradient: const LinearGradient(colors: [Color(0xFF10B981), Color(0xFF34D399)]),
                    barWidth: 4,
                    isStrokeCapRound: true,
                    dotData: FlDotData(show: true, getDotPainter: (s, p, b, i) => FlDotCirclePainter(radius: 4, color: Colors.white, strokeWidth: 2, strokeColor: const Color(0xFF10B981))),
                    belowBarData: BarAreaData(
                      show: true,
                      gradient: LinearGradient(colors: [const Color(0xFF10B981).withOpacity(0.2), const Color(0xFF10B981).withOpacity(0.0)], begin: Alignment.topCenter, end: Alignment.bottomCenter),
                    ),
                  ),
                ],
                lineTouchData: LineTouchData(
                  touchTooltipData: LineTouchTooltipData(
                    getTooltipColor: (spot) => const Color(0xFF0F172A),
                    getTooltipItems: (touchedSpots) {
                      return touchedSpots.map((spot) {
                        return LineTooltipItem(
                          "Revenue: \u20B9${spot.y.toStringAsFixed(0)}",
                          const TextStyle(color: Colors.white, fontWeight: FontWeight.bold, fontSize: 11),
                        );
                      }).toList();
                    },
                  ),
                ),
              ),
            ),
          ),
          const SizedBox(height: 16),
          Row(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              _indicator(const Color(0xFF10B981), "Net Clinical Revenue Stream (Per Transaction)"),
            ],
          ),
        ],
      ),
    );
  }

  Widget _indicator(Color color, String label) {
    return Row(
      children: [
        Container(width: 12, height: 4, decoration: BoxDecoration(color: color, borderRadius: BorderRadius.circular(2))),
        const SizedBox(width: 8),
        Text(label, style: const TextStyle(fontSize: 10, color: Color(0xFF94A3B8), fontWeight: FontWeight.bold)),
      ],
    );
  }
}
